# Generated by Django 4.0.3 on 2022-03-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('tipo', models.IntegerField(verbose_name='Tipo')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100, verbose_name='Nombre_Unico')),
                ('producto', models.CharField(max_length=40, verbose_name='Producto')),
                ('fecha_pedido', models.DateTimeField(verbose_name='Fecha_Pedido')),
                ('total', models.IntegerField(verbose_name='Monto_Pagado')),
                ('prioridad', models.IntegerField(null=True, verbose_name='Prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock_Disponible')),
                ('imagen', models.ImageField(upload_to='imagenes_productos/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('imagen', models.ImageField(upload_to='imagenes_servicio/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unico', models.CharField(max_length=100, unique=True, verbose_name='Nombre_Unico')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('sexo', models.IntegerField(verbose_name='Sexo')),
                ('celular', models.CharField(max_length=9, verbose_name='Celular')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
        ),
    ]
