# Generated by Django 4.0.3 on 2022-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
    ]
