# Generated by Django 4.0.3 on 2022-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0003_clientes_remove_usuarios_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre Promoción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha Fin')),
                ('porcentaje_descuento', models.IntegerField(default=0, verbose_name='Porcentaje de Descuento')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
