# Generated by Django 4.0.3 on 2022-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0004_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='Preparando', max_length=100, verbose_name='Estado Pedido'),
        ),
    ]
