# Generated by Django 4.0.3 on 2022-03-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0007_alter_bandeja_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='suscrtio',
            new_name='suscrito',
        ),
    ]
