# Generated by Django 4.0.3 on 2022-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0008_rename_suscrtio_clientes_suscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero_seguimiento',
            field=models.CharField(max_length=100, null=True, verbose_name='Número de Seguimiento'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='prioridad',
            field=models.IntegerField(default=0, verbose_name='Prioridad'),
        ),
    ]
