# Generated by Django 4.0.3 on 2022-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0009_pedidos_numero_seguimiento_alter_pedidos_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.DateTimeField(null=True, verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name='Fecha Pedido'),
        ),
    ]
