# Generated by Django 4.0.3 on 2022-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0010_pedidos_fecha_entrega_alter_pedidos_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_entrega',
            field=models.DateTimeField(default=0, null=True, verbose_name='Fecha Entrega'),
        ),
    ]
