# Generated by Django 4.0.3 on 2022-04-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0012_alter_clientes_promocionados_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/imagenes_productos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/imagenes_servicio/', verbose_name='Imagen'),
        ),
    ]
