# Generated by Django 4.0.3 on 2022-04-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0014_alter_productos_imagen_alter_servicios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeja',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
