# Generated by Django 4.0.3 on 2022-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0015_bandeja_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.IntegerField(verbose_name='Precio Unitario')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
        ),
        migrations.AlterField(
            model_name='bandeja',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
