# Generated by Django 4.0.3 on 2022-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0016_carrito_alter_bandeja_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='producto',
            field=models.TextField(verbose_name='Producto'),
        ),
    ]
