# Generated by Django 4.0.3 on 2022-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0019_pedidos_calle_envio_pedidos_ciudad_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes_promocionados',
            name='promocion_name',
            field=models.TextField(default='Promoción', verbose_name='Nombre de la promocion'),
        ),
    ]
